@startuml
control API
control client
database Database

API -> client: HTTP request
client -> client: Handle request data - parse, clean, modify
client -> Database: QUERY, ADD, DELETE, JOIN ...
client <-- Database: id, items, errors
client -> client: Handle request data - parse, clean, modify
API <-- client: HTTP response
@enduml
